{{- $root := . -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:

      {{- if .Values.mounts }}
      volumes:
        {{- range $name, $mount := .Values.mounts }}
        - name: {{ $name }}
{{ tpl (toYaml .definition) $root | indent 10 }}
        {{- end }}
      {{- end }}

      {{- if .Values.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.pullSecrets }}
        - name: {{ template "fullname" $root }}-{{ .name }}
      {{- end }}
      {{- end }}

      {{- if .Values.initContainer }}
      initContainers:
        {{- range $name, $container := .Values.initContainer }}
        - name: {{ $name }}
{{ include "container" (dict "c" $container "root" $root) | indent 10 }}
        {{- end }}
      {{- end }}

      containers:
        {{- range $name, $container := .Values.container }}
        - name: {{ $name }}
{{ include "container" (dict "c" $container "root" $root) | indent 10 }}
        {{- end }}
